# Uncomment the next line to define a global platform for your project
platform :ios, '12.0'

target 'terremotos' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for terremotos
  pod 'Alamofire','~> 5.2'
  pod 'JSON'
  pod 'SwiftyJSON'

end
